version: "3"
services:
  db-service:
   image: ionelanicuta05/happystore:latest
   deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
   ports:
     - "9000:3306"
   networks:
     - dbnet
networks:
  dbnet:
